//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TreasureHuntDesktopApplication.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TreasureHuntEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TreasureHuntEntities object using the connection string found in the 'TreasureHuntEntities' section of the application configuration file.
        /// </summary>
        public TreasureHuntEntities() : base("name=TreasureHuntEntities", "TreasureHuntEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TreasureHuntEntities object.
        /// </summary>
        public TreasureHuntEntities(string connectionString) : base(connectionString, "TreasureHuntEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TreasureHuntEntities object.
        /// </summary>
        public TreasureHuntEntities(EntityConnection connection) : base(connection, "TreasureHuntEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<hunt> hunts
        {
            get
            {
                if ((_hunts == null))
                {
                    _hunts = base.CreateObjectSet<hunt>("hunts");
                }
                return _hunts;
            }
        }
        private ObjectSet<hunt> _hunts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<huntparticipant> huntparticipants
        {
            get
            {
                if ((_huntparticipants == null))
                {
                    _huntparticipants = base.CreateObjectSet<huntparticipant>("huntparticipants");
                }
                return _huntparticipants;
            }
        }
        private ObjectSet<huntparticipant> _huntparticipants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<huntquestion> huntquestions
        {
            get
            {
                if ((_huntquestions == null))
                {
                    _huntquestions = base.CreateObjectSet<huntquestion>("huntquestions");
                }
                return _huntquestions;
            }
        }
        private ObjectSet<huntquestion> _huntquestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<question> questions
        {
            get
            {
                if ((_questions == null))
                {
                    _questions = base.CreateObjectSet<question>("questions");
                }
                return _questions;
            }
        }
        private ObjectSet<question> _questions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<role> roles
        {
            get
            {
                if ((_roles == null))
                {
                    _roles = base.CreateObjectSet<role>("roles");
                }
                return _roles;
            }
        }
        private ObjectSet<role> _roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userhunt> userhunts
        {
            get
            {
                if ((_userhunts == null))
                {
                    _userhunts = base.CreateObjectSet<userhunt>("userhunts");
                }
                return _userhunts;
            }
        }
        private ObjectSet<userhunt> _userhunts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userrole> userroles
        {
            get
            {
                if ((_userroles == null))
                {
                    _userroles = base.CreateObjectSet<userrole>("userroles");
                }
                return _userroles;
            }
        }
        private ObjectSet<userrole> _userroles;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the hunts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohunts(hunt hunt)
        {
            base.AddObject("hunts", hunt);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the huntparticipants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohuntparticipants(huntparticipant huntparticipant)
        {
            base.AddObject("huntparticipants", huntparticipant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the huntquestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohuntquestions(huntquestion huntquestion)
        {
            base.AddObject("huntquestions", huntquestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the questions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToquestions(question question)
        {
            base.AddObject("questions", question);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToroles(role role)
        {
            base.AddObject("roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userhunts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserhunts(userhunt userhunt)
        {
            base.AddObject("userhunts", userhunt);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userroles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserroles(userrole userrole)
        {
            base.AddObject("userroles", userrole);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="virapy_treasurehuntdbModel", Name="hunt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class hunt : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new hunt object.
        /// </summary>
        /// <param name="huntId">Initial value of the HuntId property.</param>
        /// <param name="huntName">Initial value of the HuntName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="huntDescription">Initial value of the HuntDescription property.</param>
        public static hunt Createhunt(global::System.Int64 huntId, global::System.String huntName, global::System.String password, global::System.String huntDescription)
        {
            hunt hunt = new hunt();
            hunt.HuntId = huntId;
            hunt.HuntName = huntName;
            hunt.Password = password;
            hunt.HuntDescription = huntDescription;
            return hunt;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 HuntId
        {
            get
            {
                return _HuntId;
            }
            set
            {
                if (_HuntId != value)
                {
                    OnHuntIdChanging(value);
                    ReportPropertyChanging("HuntId");
                    _HuntId = StructuralObject.SetValidValue(value, "HuntId");
                    ReportPropertyChanged("HuntId");
                    OnHuntIdChanged();
                }
            }
        }
        private global::System.Int64 _HuntId;
        partial void OnHuntIdChanging(global::System.Int64 value);
        partial void OnHuntIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HuntName
        {
            get
            {
                return _HuntName;
            }
            set
            {
                OnHuntNameChanging(value);
                ReportPropertyChanging("HuntName");
                _HuntName = StructuralObject.SetValidValue(value, false, "HuntName");
                ReportPropertyChanged("HuntName");
                OnHuntNameChanged();
            }
        }
        private global::System.String _HuntName;
        partial void OnHuntNameChanging(global::System.String value);
        partial void OnHuntNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HuntDescription
        {
            get
            {
                return _HuntDescription;
            }
            set
            {
                OnHuntDescriptionChanging(value);
                ReportPropertyChanging("HuntDescription");
                _HuntDescription = StructuralObject.SetValidValue(value, false, "HuntDescription");
                ReportPropertyChanged("HuntDescription");
                OnHuntDescriptionChanged();
            }
        }
        private global::System.String _HuntDescription;
        partial void OnHuntDescriptionChanging(global::System.String value);
        partial void OnHuntDescriptionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="virapy_treasurehuntdbModel", Name="huntparticipant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class huntparticipant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new huntparticipant object.
        /// </summary>
        /// <param name="huntParticipantId">Initial value of the HuntParticipantId property.</param>
        /// <param name="huntId">Initial value of the HuntId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="tally">Initial value of the Tally property.</param>
        /// <param name="elapsedTime">Initial value of the ElapsedTime property.</param>
        public static huntparticipant Createhuntparticipant(global::System.Int64 huntParticipantId, global::System.Int64 huntId, global::System.Int64 userId, global::System.Int64 tally, global::System.Single elapsedTime)
        {
            huntparticipant huntparticipant = new huntparticipant();
            huntparticipant.HuntParticipantId = huntParticipantId;
            huntparticipant.HuntId = huntId;
            huntparticipant.UserId = userId;
            huntparticipant.Tally = tally;
            huntparticipant.ElapsedTime = elapsedTime;
            return huntparticipant;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 HuntParticipantId
        {
            get
            {
                return _HuntParticipantId;
            }
            set
            {
                if (_HuntParticipantId != value)
                {
                    OnHuntParticipantIdChanging(value);
                    ReportPropertyChanging("HuntParticipantId");
                    _HuntParticipantId = StructuralObject.SetValidValue(value, "HuntParticipantId");
                    ReportPropertyChanged("HuntParticipantId");
                    OnHuntParticipantIdChanged();
                }
            }
        }
        private global::System.Int64 _HuntParticipantId;
        partial void OnHuntParticipantIdChanging(global::System.Int64 value);
        partial void OnHuntParticipantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 HuntId
        {
            get
            {
                return _HuntId;
            }
            set
            {
                OnHuntIdChanging(value);
                ReportPropertyChanging("HuntId");
                _HuntId = StructuralObject.SetValidValue(value, "HuntId");
                ReportPropertyChanged("HuntId");
                OnHuntIdChanged();
            }
        }
        private global::System.Int64 _HuntId;
        partial void OnHuntIdChanging(global::System.Int64 value);
        partial void OnHuntIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Tally
        {
            get
            {
                return _Tally;
            }
            set
            {
                OnTallyChanging(value);
                ReportPropertyChanging("Tally");
                _Tally = StructuralObject.SetValidValue(value, "Tally");
                ReportPropertyChanged("Tally");
                OnTallyChanged();
            }
        }
        private global::System.Int64 _Tally;
        partial void OnTallyChanging(global::System.Int64 value);
        partial void OnTallyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single ElapsedTime
        {
            get
            {
                return _ElapsedTime;
            }
            set
            {
                OnElapsedTimeChanging(value);
                ReportPropertyChanging("ElapsedTime");
                _ElapsedTime = StructuralObject.SetValidValue(value, "ElapsedTime");
                ReportPropertyChanged("ElapsedTime");
                OnElapsedTimeChanged();
            }
        }
        private global::System.Single _ElapsedTime;
        partial void OnElapsedTimeChanging(global::System.Single value);
        partial void OnElapsedTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value, "StartTime");
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.Double> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.Double> value);
        partial void OnStartTimeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="virapy_treasurehuntdbModel", Name="huntquestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class huntquestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new huntquestion object.
        /// </summary>
        /// <param name="huntQuestionId">Initial value of the HuntQuestionId property.</param>
        /// <param name="huntId">Initial value of the HuntId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static huntquestion Createhuntquestion(global::System.Int64 huntQuestionId, global::System.Int64 huntId, global::System.Int64 questionId)
        {
            huntquestion huntquestion = new huntquestion();
            huntquestion.HuntQuestionId = huntQuestionId;
            huntquestion.HuntId = huntId;
            huntquestion.QuestionId = questionId;
            return huntquestion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 HuntQuestionId
        {
            get
            {
                return _HuntQuestionId;
            }
            set
            {
                if (_HuntQuestionId != value)
                {
                    OnHuntQuestionIdChanging(value);
                    ReportPropertyChanging("HuntQuestionId");
                    _HuntQuestionId = StructuralObject.SetValidValue(value, "HuntQuestionId");
                    ReportPropertyChanged("HuntQuestionId");
                    OnHuntQuestionIdChanged();
                }
            }
        }
        private global::System.Int64 _HuntQuestionId;
        partial void OnHuntQuestionIdChanging(global::System.Int64 value);
        partial void OnHuntQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 HuntId
        {
            get
            {
                return _HuntId;
            }
            set
            {
                OnHuntIdChanging(value);
                ReportPropertyChanging("HuntId");
                _HuntId = StructuralObject.SetValidValue(value, "HuntId");
                ReportPropertyChanged("HuntId");
                OnHuntIdChanged();
            }
        }
        private global::System.Int64 _HuntId;
        partial void OnHuntIdChanging(global::System.Int64 value);
        partial void OnHuntIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Int64 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int64 value);
        partial void OnQuestionIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="virapy_treasurehuntdbModel", Name="question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class question : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new question object.
        /// </summary>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="question1">Initial value of the Question1 property.</param>
        /// <param name="uRL">Initial value of the URL property.</param>
        public static question Createquestion(global::System.Int64 questionId, global::System.String question1, global::System.String uRL)
        {
            question question = new question();
            question.QuestionId = questionId;
            question.Question1 = question1;
            question.URL = uRL;
            return question;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                if (_QuestionId != value)
                {
                    OnQuestionIdChanging(value);
                    ReportPropertyChanging("QuestionId");
                    _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                    ReportPropertyChanged("QuestionId");
                    OnQuestionIdChanged();
                }
            }
        }
        private global::System.Int64 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int64 value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Question1
        {
            get
            {
                return _Question1;
            }
            set
            {
                OnQuestion1Changing(value);
                ReportPropertyChanging("Question1");
                _Question1 = StructuralObject.SetValidValue(value, false, "Question1");
                ReportPropertyChanged("Question1");
                OnQuestion1Changed();
            }
        }
        private global::System.String _Question1;
        partial void OnQuestion1Changing(global::System.String value);
        partial void OnQuestion1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, false, "URL");
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="virapy_treasurehuntdbModel", Name="role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new role object.
        /// </summary>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static role Createrole(global::System.Int64 roleId, global::System.String name)
        {
            role role = new role();
            role.RoleId = roleId;
            role.Name = name;
            return role;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value, "RoleId");
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int64 _RoleId;
        partial void OnRoleIdChanging(global::System.Int64 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="virapy_treasurehuntdbModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static user Createuser(global::System.Int64 userId, global::System.String name, global::System.String email, global::System.String password)
        {
            user user = new user();
            user.UserId = userId;
            user.Name = name;
            user.Email = email;
            user.Password = password;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="virapy_treasurehuntdbModel", Name="userhunt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userhunt : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userhunt object.
        /// </summary>
        /// <param name="userHuntId">Initial value of the UserHuntId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="huntId">Initial value of the HuntId property.</param>
        /// <param name="userRoleId">Initial value of the UserRoleId property.</param>
        public static userhunt Createuserhunt(global::System.Int64 userHuntId, global::System.Int64 userId, global::System.Int64 huntId, global::System.Int64 userRoleId)
        {
            userhunt userhunt = new userhunt();
            userhunt.UserHuntId = userHuntId;
            userhunt.UserId = userId;
            userhunt.HuntId = huntId;
            userhunt.UserRoleId = userRoleId;
            return userhunt;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserHuntId
        {
            get
            {
                return _UserHuntId;
            }
            set
            {
                if (_UserHuntId != value)
                {
                    OnUserHuntIdChanging(value);
                    ReportPropertyChanging("UserHuntId");
                    _UserHuntId = StructuralObject.SetValidValue(value, "UserHuntId");
                    ReportPropertyChanged("UserHuntId");
                    OnUserHuntIdChanged();
                }
            }
        }
        private global::System.Int64 _UserHuntId;
        partial void OnUserHuntIdChanging(global::System.Int64 value);
        partial void OnUserHuntIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 HuntId
        {
            get
            {
                return _HuntId;
            }
            set
            {
                OnHuntIdChanging(value);
                ReportPropertyChanging("HuntId");
                _HuntId = StructuralObject.SetValidValue(value, "HuntId");
                ReportPropertyChanged("HuntId");
                OnHuntIdChanged();
            }
        }
        private global::System.Int64 _HuntId;
        partial void OnHuntIdChanging(global::System.Int64 value);
        partial void OnHuntIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserRoleId
        {
            get
            {
                return _UserRoleId;
            }
            set
            {
                OnUserRoleIdChanging(value);
                ReportPropertyChanging("UserRoleId");
                _UserRoleId = StructuralObject.SetValidValue(value, "UserRoleId");
                ReportPropertyChanged("UserRoleId");
                OnUserRoleIdChanged();
            }
        }
        private global::System.Int64 _UserRoleId;
        partial void OnUserRoleIdChanging(global::System.Int64 value);
        partial void OnUserRoleIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="virapy_treasurehuntdbModel", Name="userrole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userrole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userrole object.
        /// </summary>
        /// <param name="userRoleId">Initial value of the UserRoleId property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static userrole Createuserrole(global::System.Int64 userRoleId, global::System.Int64 roleId, global::System.Int64 userId)
        {
            userrole userrole = new userrole();
            userrole.UserRoleId = userRoleId;
            userrole.RoleId = roleId;
            userrole.UserId = userId;
            return userrole;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserRoleId
        {
            get
            {
                return _UserRoleId;
            }
            set
            {
                if (_UserRoleId != value)
                {
                    OnUserRoleIdChanging(value);
                    ReportPropertyChanging("UserRoleId");
                    _UserRoleId = StructuralObject.SetValidValue(value, "UserRoleId");
                    ReportPropertyChanged("UserRoleId");
                    OnUserRoleIdChanged();
                }
            }
        }
        private global::System.Int64 _UserRoleId;
        partial void OnUserRoleIdChanging(global::System.Int64 value);
        partial void OnUserRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value, "RoleId");
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int64 _RoleId;
        partial void OnRoleIdChanging(global::System.Int64 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();

        #endregion

    }

    #endregion

}
