//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreasureHuntDesktopApplication.FullClient.TreasureHuntService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TreasureHuntService.ITreasureHuntService")]
    public interface ITreasureHuntService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/DoWork", ReplyAction="http://tempuri.org/ITreasureHuntService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreasureHuntService/DoWork", ReplyAction="http://tempuri.org/ITreasureHuntService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITreasureHuntServiceChannel : TreasureHuntDesktopApplication.FullClient.TreasureHuntService.ITreasureHuntService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TreasureHuntServiceClient : System.ServiceModel.ClientBase<TreasureHuntDesktopApplication.FullClient.TreasureHuntService.ITreasureHuntService>, TreasureHuntDesktopApplication.FullClient.TreasureHuntService.ITreasureHuntService {
        
        public TreasureHuntServiceClient() {
        }
        
        public TreasureHuntServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TreasureHuntServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TreasureHuntServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TreasureHuntServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
